CLR_INVERT    := \033[7m
CLR_UNDERLINE := \033[4m

CLR_GREEN := \033[32m
CLR_WHITE := \033[0m
CLR_BLUE  := \033[34m

MSG_SUCCESS        := [$(CLR_GREEN)✓$(CLR_WHITE)]
MSG_BSUCCESS       := [$(CLR_BLUE)✓$(CLR_WHITE)]
MSG_SUCCESS_NO_CLR := [✓]
